# Site settings
author: Howard Suarez
title: Project 2020
header-img: img/home-bg.png
email: howardesuarez@gmail.com
copyright_name: Howard Suarez
description: > # this means to ignore newlines until "baseurl:"
  A collection of projects from the Software Engineering program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  howardesuarez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
